url: "" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "" #Use this for development
baseurl: "/fgquickstart" # subdirectory (like /blog), use it for production. REPLACE with your repo name
theme: jekyll-theme-forestguild
markdown: kramdown
compress_html:
  clippings: all
  comments: all
  startings: all
  endings: all
  blanklines: false
  profile: false


ui:
  brand: Сайт гильдии #Brand name or short name, example: website name 'Guild "Lala Land" @ EU Galakrond' may use 'Lala Land' as brand name
  addon: 8.1.5 #Current WoW Addon
  meta: #Website meta tags
    lang: ru #Website language code
    locale: ru_RU #Website locale code, examples: ru_RU, en_GB, en_US
    title: Создание сайта гильдии #Website title
    description: Инструкция по созданию веб-сайта для своей гильдии. #Website meta description
    article: #Website articles meta
      category: Гайд #Articles' category
      tags: ['Гайд', 'Ruby', 'Jekyll', 'World of Warcraft'] #Articles' tags
  images: #Website images (logos, etc) relative to site.url
    logo: #General website logo
      url: /assets/img/logo.png
      type: image/png #Image MIME-type
      has_svg: false #If your logo has SVG symbol variant, place it on /assets/logo.svg
    favicon:
      url: /favicon.ico #NOTE: best path is /favicon.ico, because some browsers will ignore that setting and try to load /favicon.ico
      type: image/x-icon
  verification: #Website verification HTML meta-tags
    yandex: 0e76a0024o392418 # REPLACE with your value
    google: GuZthk__XEN9oS-nLwAbRIP2wVBFXVr25u0zwJkUKdE # REPLACE with your value
  analytics: # Website analytics. Supported only Yandex.Metrika right now
    yandex: 50342920 # REPLACE with your value
  ads: # Website ads. Supported only Yandex.Direct/Adfox
    type: yandex
    fallback: https://patreon.com/rakshazi #If person uses adblock he will see block under content with offer disable adblock or fund website with patreon or any other way
    page: # General page (like wiki article) ad blocks
      bottom: R-A-223582-4 # Block ID, under content
    amphtml: #AMP html blocks
      top: R-A-223582-2 #Block ID, above content, ONLY 300x250px
      bottom: R-A-223582-3 #Block ID, under content, ONLY 300x250px

# Attendance tracker, docs: https://github.com/forestguild/attendance
attendance:
  guild: 263566 #Warcraft Logs Guild ID
  max: 10 # Maximum fights in report
  team: 0 # Warcraft Logs TEAM ID
  name: main # Team name
  twinks:
    Имя: ['Имямонк', 'Имяхант', 'Имялок']

# WoW daily data from wowhead.com, docs: https://github.com/forestguild/wowdaily
wowdaily:
  region: eu
  lang: ru

# Guild progress updater, docs: https://github.com/forestguild/updater
wowupdater:
  region: "eu" #Region code: eu/us
  realm: "галакронд" #Realm name (translated)
  realm-id: 607 # Raider.IO realm id
  guild: "Ясный Лес" # Guild name
